# التعديل على NEWS_URL لمنع 404
BASE_URL = "https://www.marca.com"
NEWS_URL = f"{BASE_URL}/futbol/real-madrid.html"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
        }
        
        # --- الجزء الخاص بكودك من سطر 142 لآخر الملف مع تصحيح الأخطاء ---
        
                        continue
                                    print("Url not in database - Working")
                                                
                                                            # حماية الترجمة من الـ Rate Limit عشان ما ترميش Exception وتخطي المقال
                                                                        try:
                                                                                        caption, authorName = get_article_data(url)  # أو الدالة اللي بتجيب الداتا عندك
                                                                                                    except Exception as e:
                                                                                                                    print(f"Exception ERR: {e}")
                                                                                                                                    caption, authorName = None, None
                                                                                                                                    
                                                                                                                                                if not all([caption, authorName]):
                                                                                                                                                                print("❗ No data available - Skipping")
                                                                                                                                                                                print(f"🔗 URL for checking: {url}\n")
                                                                                                                                                                                                continue
                                                                                                                                                                                                
                                                                                                                                                                                                            imageUrl = articlesImageFetcher(url)
                                                                                                                                                                                                                        if not imageUrl:
                                                                                                                                                                                                                                        continue
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                    imageUrl = re.sub(r"(?<=/)\d+x\d+(?=/)", "1200x675", imageUrl)
                                                                                                                                                                                                                                                                imageResponse = requests.get(imageUrl, headers=HEADERS)
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                            if not imageResponse.status_code == 200:
                                                                                                                                                                                                                                                                                            print("Fail to get image")
                                                                                                                                                                                                                                                                                                            continue
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                        photo = BytesIO(imageResponse.content)
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                    # Send to telegram:
                                                                                                                                                                                                                                                                                                                                                print("Send message to telegram...")
                                                                                                                                                                                                                                                                                                                                                            status = asyncio.run(
                                                                                                                                                                                                                                                                                                                                                                            send_photo_message(
                                                                                                                                                                                                                                                                                                                                                                                                token=TELEGRAM_BOT_TOKEN,
                                                                                                                                                                                                                                                                                                                                                                                                                    chat_id=TELEGRAM_CHAT_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                        caption=caption,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            photo_url=photo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                source_url=url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    buttonText=f"Read on {authorName}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if status == True or status == "success":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Save to database:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Save url to database...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            save_to_database(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                collection=realMadridCollection,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data={"article_url": url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("✅ Url saved to database")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Message fail to send")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n✅ All Done - Exiting")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise Exception(f"🚫 Request Fail: {response.status_code} - Exiting...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
