BASE_URL = "https://mostaql.com"
DEVELOPERMENT_URL = f"{BASE_URL}/projects?category=development&sort=latest"
HEADERS = {"User-Agent": "Mozilla/5.0"}
COLLECTION_NAME = "freelance"
SOURCE_NAME = "mostql"
FORBIDDEN_WORDS = [
    "n8n",
    "bim",
    "ووردبريس",
    "وورد بريس",
    "wordpress",
    "unity",
    "سلة",
    "سله",
    "تطبيق",
    "موبايل",
    "native",
    "بايثون",
    "اكسل",
    "أكسل",
    "excel",
    "العاب",
    "ألعاب",
    "لعبة",
    "بوت",
    "دروب",
    "php",
    "الاصطناعي",
    "دروب شوبنق",
    "ios",
    "nuxt.js",
    "astro",
    "odoo",
    "أودو",
    "erp",
    "erb",
    "وردبريس",
    "لارافيل",
    "Flutter",
    "asp",
    "ووكوميرس",
    "زد",
    "power bi",
    "دردشة",
    "معلومات جغرافية",
]  # ! Write words as lowercase
