name: Run All Scripts

on:
  schedule:
    - cron: "*/10 * * * *" # أي وقت دلوقتي
  workflow_dispatch:

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: pip install -r requirements.txt

      - name: Run all scripts
        run: |
          python -m scripts.real_madrid.official_news
          python -m scripts.real_madrid.marca
          python -m scripts.real_madrid.as
          python -m scripts.cve.nvd_api
          python -m scripts.masr.gate_ahram
